# StandAPI configuration file

#Distance over which PacketStands will be visible
#Doesn't affect performance
RenderDistance: 9216

#Should plugin save stands and load them on startup?
SavingEnabled: true