# StandAPI configuration file

#Distance in blocks over which PacketStands will be visible
#Doesn't affect performance
RenderDistance: 192

#Should plugin save stands and load them on startup?
SavingEnabled: true

#Is test mode enabled
TestMode: false