name: StandAPI
version: '${project.version}'
main: com.github.justadeni.standapi.StandAPI
api-version: '1.19'
depend: [ProtocolLib]
commands:
  standapi:
    description: command used to test functionality of API
    permission: standapi.admin